/* the file name county_market_tracker.tsv must be replaced with a real absolute file path */

USE `housing`;

CREATE OR REPLACE TABLE `housing`.`county_market_tracker` (
    period_begin DATE,
    period_end DATE,
    period_duration INT,
    region_type VARCHAR(32),
    region_type_id INT,
    table_id INT,
    is_seasonally_adjusted VARCHAR(32),
    region VARCHAR(32),
    city VARCHAR(32),
    state VARCHAR(32),
    state_code VARCHAR(32),
    property_type VARCHAR(32),
    property_type_id INT,
    median_sale_price DECIMAL(32, 24),
    median_sale_price_mom DECIMAL(32, 24),
    median_sale_price_yoy DECIMAL(32, 24),
    median_list_price DECIMAL(32, 24),
    median_list_price_mom DECIMAL(32, 24),
    median_list_price_yoy DECIMAL(32, 24),
    median_ppsf DECIMAL(32, 24),
    median_ppsf_mom DECIMAL(32, 24),
    median_ppsf_yoy DECIMAL(32, 24),
    median_list_ppsf DECIMAL(32, 24),
    median_list_ppsf_mom DECIMAL(32, 24),
    median_list_ppsf_yoy DECIMAL(32, 24),
    homes_sold DECIMAL(32, 24),
    homes_sold_mom DECIMAL(32, 24),
    homes_sold_yoy DECIMAL(32, 24),
    pending_sales DECIMAL(32, 24),
    pending_sales_mom DECIMAL(32, 24),
    pending_sales_yoy DECIMAL(32, 24),
    new_listings DECIMAL(32, 24),
    new_listings_mom DECIMAL(32, 24),
    new_listings_yoy DECIMAL(32, 24),
    inventory DECIMAL(32, 24),
    inventory_mom DECIMAL(32, 24),
    inventory_yoy DECIMAL(32, 24),
    months_of_supply DECIMAL(32, 24),
    months_of_supply_mom DECIMAL(32, 24),
    months_of_supply_yoy DECIMAL(32, 24),
    median_dom DECIMAL(32, 24),
    median_dom_mom DECIMAL(32, 24),
    median_dom_yoy DECIMAL(32, 24),
    avg_sale_to_list DECIMAL(32, 24),
    avg_sale_to_list_mom DECIMAL(32, 24),
    avg_sale_to_list_yoy DECIMAL(32, 24),
    sold_above_list DECIMAL(32, 24),
    sold_above_list_mom DECIMAL(32, 24),
    sold_above_list_yoy DECIMAL(32, 24),
    price_drops DECIMAL(32, 24),
    price_drops_mom DECIMAL(32, 24),
    price_drops_yoy DECIMAL(32, 24),
    off_market_in_two_weeks DECIMAL(32, 24),
    off_market_in_two_weeks_mom DECIMAL(32, 24),
    off_market_in_two_weeks_yoy DECIMAL(32, 24),
    parent_metro_region VARCHAR(32),
    parent_metro_region_metro_code INT,
    last_updated DATETIME
);

SELECT * FROM county_market_tracker LIMIT 10;

LOAD DATA LOW_PRIORITY LOCAL INFILE 'county_market_tracker.tsv'
INTO TABLE `housing`.`county_market_tracker`
CHARACTER SET ASCII
FIELDS TERMINATED BY '\t'
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
    @period_begin,
    @period_end,
    @period_duration,
    @region_type,
    @region_type_id,
    @table_id,
    @is_seasonally_adjusted,
    @region,
    @city,
    @state,
    @state_code,
    @property_type,
    @property_type_id,
    @median_sale_price,
    @median_sale_price_mom,
    @median_sale_price_yoy,
    @median_list_price,
    @median_list_price_mom,
    @median_list_price_yoy,
    @median_ppsf,
    @median_ppsf_mom,
    @median_ppsf_yoy,
    @median_list_ppsf,
    @median_list_ppsf_mom,
    @median_list_ppsf_yoy,
    @homes_sold,
    @homes_sold_mom,
    @homes_sold_yoy,
    @pending_sales,
    @pending_sales_mom,
    @pending_sales_yoy,
    @new_listings,
    @new_listings_mom,
    @new_listings_yoy,
    @inventory,
    @inventory_mom,
    @inventory_yoy,
    @months_of_supply,
    @months_of_supply_mom,
    @months_of_supply_yoy,
    @median_dom,
    @median_dom_mom,
    @median_dom_yoy,
    @avg_sale_to_list,
    @avg_sale_to_list_mom,
    @avg_sale_to_list_yoy,
    @sold_above_list,
    @sold_above_list_mom,
    @sold_above_list_yoy,
    @price_drops,
    @price_drops_mom,
    @price_drops_yoy,
    @off_market_in_two_weeks,
    @off_market_in_two_weeks_mom,
    @off_market_in_two_weeks_yoy,
    @parent_metro_region,
    @parent_metro_region_metro_code,
    @last_updated
)
SET
`period_begin` = NULLIF(@period_begin, ''),
`period_end` = NULLIF(@period_end, ''),
`period_duration` = NULLIF(@period_duration, ''),
`region_type` = NULLIF(@region_type, ''),
`region_type_id` = NULLIF(@region_type_id, ''),
`table_id` = NULLIF(@table_id, ''),
`is_seasonally_adjusted` = NULLIF(@is_seasonally_adjusted, ''),
`region` = NULLIF(@region, ''),
`city` = NULLIF(@city, ''),
`state` = NULLIF(@state, ''),
`state_code` = NULLIF(@state_code, ''),
`property_type` = NULLIF(@property_type, ''),
`property_type_id` = NULLIF(@property_type_id, ''),
`median_sale_price` = NULLIF(@median_sale_price, ''),
`median_sale_price_mom` = NULLIF(@median_sale_price_mom, ''),
`median_sale_price_yoy` = NULLIF(@median_sale_price_yoy, ''),
`median_list_price` = NULLIF(@median_list_price, ''),
`median_list_price_mom` = NULLIF(@median_list_price_mom, ''),
`median_list_price_yoy` = NULLIF(@median_list_price_yoy, ''),
`median_ppsf` = NULLIF(@median_ppsf, ''),
`median_ppsf_mom` = NULLIF(@median_ppsf_mom, ''),
`median_ppsf_yoy` = NULLIF(@median_ppsf_yoy, ''),
`median_list_ppsf` = NULLIF(@median_list_ppsf, ''),
`median_list_ppsf_mom` = NULLIF(@median_list_ppsf_mom, ''),
`median_list_ppsf_yoy` = NULLIF(@median_list_ppsf_yoy, ''),
`homes_sold` = NULLIF(@homes_sold, ''),
`homes_sold_mom` = NULLIF(@homes_sold_mom, ''),
`homes_sold_yoy` = NULLIF(@homes_sold_yoy, ''),
`pending_sales` = NULLIF(@pending_sales, ''),
`pending_sales_mom` = NULLIF(@pending_sales_mom, ''),
`pending_sales_yoy` = NULLIF(@pending_sales_yoy, ''),
`new_listings` = NULLIF(@new_listings, ''),
`new_listings_mom` = NULLIF(@new_listings_mom, ''),
`new_listings_yoy` = NULLIF(@new_listings_yoy, ''),
`inventory` = NULLIF(@inventory, ''),
`inventory_mom` = NULLIF(@inventory_mom, ''),
`inventory_yoy` = NULLIF(@inventory_yoy, ''),
`months_of_supply` = NULLIF(@months_of_supply, ''),
`months_of_supply_mom` = NULLIF(@months_of_supply_mom, ''),
`months_of_supply_yoy` = NULLIF(@months_of_supply_yoy, ''),
`median_dom` = NULLIF(@median_dom, ''),
`median_dom_mom` = NULLIF(@median_dom_mom, ''),
`median_dom_yoy` = NULLIF(@median_dom_yoy, ''),
`avg_sale_to_list` = NULLIF(@avg_sale_to_list, ''),
`avg_sale_to_list_mom` = NULLIF(@avg_sale_to_list_mom, ''),
`avg_sale_to_list_yoy` = NULLIF(@avg_sale_to_list_yoy, ''),
`sold_above_list` = NULLIF(@sold_above_list, ''),
`sold_above_list_mom` = NULLIF(@sold_above_list_mom, ''),
`sold_above_list_yoy` = NULLIF(@sold_above_list_yoy, ''),
`price_drops` = NULLIF(@price_drops, ''),
`price_drops_mom` = NULLIF(@price_drops_mom, ''),
`price_drops_yoy` = NULLIF(@price_drops_yoy, ''),
`off_market_in_two_weeks` = NULLIF(@off_market_in_two_weeks, ''),
`off_market_in_two_weeks_mom` = NULLIF(@off_market_in_two_weeks_mom, ''),
`off_market_in_two_weeks_yoy` = NULLIF(@off_market_in_two_weeks_yoy, ''),
`parent_metro_region` = NULLIF(@parent_metro_region, ''),
`parent_metro_region_metro_code` = NULLIF(@parent_metro_region_metro_code, ''),
`last_updated` = NULLIF(@last_updated, '');
