/* the file name weekly_housing_market_data_most_recent.tsv must be replaced with a real absolute file path */

USE `housing`;

CREATE OR REPLACE TABLE `housing`.`weekly_housing_market_data_most_recent` (
    region_id VARCHAR(32),
    region_type_id INT,
    region_name VARCHAR(32),
    region_type VARCHAR(32),
    period_begin DATE,
    period_end DATE,
    duration VARCHAR(32),
    total_homes_sold DECIMAL(32, 24),
    total_homes_sold_yoy DECIMAL(32, 24),
    average_homes_sold DECIMAL(32, 24),
    average_homes_sold_yoy DECIMAL(32, 24),
    total_homes_sold_with_price_drops DECIMAL(32, 24),
    total_homes_sold_with_price_drops_yoy DECIMAL(32, 24),
    average_homes_sold_with_price_drops DECIMAL(32, 24),
    average_homes_sold_with_price_drops_yoy DECIMAL(32, 24),
    percent_homes_sold_with_price_drops DECIMAL(32, 24),
    percent_homes_sold_with_price_drops_yoy DECIMAL(32, 24),
    median_sale_price DECIMAL(32, 24),
    median_sale_price_yoy DECIMAL(32, 24),
    median_sale_ppsf DECIMAL(32, 24),
    median_sale_ppsf_yoy DECIMAL(32, 24),
    median_days_to_close DECIMAL(32, 24),
    median_days_to_close_yoy DECIMAL(32, 24),
    price_drops DECIMAL(32, 24),
    price_drops_yoy DECIMAL(32, 24),
    percent_active_listings_with_price_drops DECIMAL(32, 24),
    percent_active_listings_with_price_drops_yoy DECIMAL(32, 24),
    pending_sales DECIMAL(32, 24),
    pending_sales_yoy DECIMAL(32, 24),
    median_pending_sqft DECIMAL(32, 24),
    median_pending_sqft_yoy DECIMAL(32, 24),
    off_market_in_two_weeks DECIMAL(32, 24),
    off_market_in_two_weeks_yoy DECIMAL(32, 24),
    off_market_in_one_week DECIMAL(32, 24),
    off_market_in_one_week_yoy DECIMAL(32, 24),
    percent_off_market_in_two_weeks DECIMAL(32, 24),
    percent_off_market_in_two_weeks_yoy DECIMAL(32, 24),
    percent_off_market_in_one_week DECIMAL(32, 24),
    percent_off_market_in_one_week_yoy DECIMAL(32, 24),
    total_new_listings DECIMAL(32, 24),
    total_new_listings_yoy DECIMAL(32, 24),
    average_new_listings DECIMAL(32, 24),
    average_new_listings_yoy DECIMAL(32, 24),
    median_new_listing_price DECIMAL(32, 24),
    median_new_listing_price_yoy DECIMAL(32, 24),
    median_new_listing_ppsf DECIMAL(32, 24),
    median_new_listing_ppsf_yoy DECIMAL(32, 24),
    inventory DECIMAL(32, 24),
    inventory_yoy DECIMAL(32, 24),
    total_active_listings DECIMAL(32, 24),
    total_active_listings_yoy DECIMAL(32, 24),
    active_listings DECIMAL(32, 24),
    active_listings_yoy DECIMAL(32, 24),
    age_of_inventory DECIMAL(32, 24),
    age_of_inventory_yoy DECIMAL(32, 24),
    homes_delisted DECIMAL(32, 24),
    homes_delisted_yoy DECIMAL(32, 24),
    percent_active_listings_delisted DECIMAL(32, 24),
    percent_active_listings_delisted_yoy DECIMAL(32, 24),
    median_active_list_price DECIMAL(32, 24),
    median_active_list_price_yoy DECIMAL(32, 24),
    median_active_list_ppsf DECIMAL(32, 24),
    median_active_list_ppsf_yoy DECIMAL(32, 24),
    average_of_median_list_price_amount DECIMAL(32, 24),
    average_of_median_list_price_amount_yoy DECIMAL(32, 24),
    average_of_median_offer_price_amount DECIMAL(32, 24),
    average_of_median_offer_price_amount_yoy DECIMAL(32, 24),
    avg_offer_to_list DECIMAL(32, 24),
    avg_offer_to_list_yoy DECIMAL(32, 24),
    average_sale_to_list_ratio DECIMAL(32, 24),
    average_sale_to_list_ratio_yoy DECIMAL(32, 24),
    median_days_on_market DECIMAL(32, 24),
    median_days_on_market_yoy DECIMAL(32, 24),
    pending_sales_to_sales_ratio DECIMAL(32, 24),
    pending_sales_to_sales_ratio_yoy DECIMAL(32, 24),
    months_of_supply DECIMAL(32, 24),
    months_of_supply_yoy DECIMAL(32, 24),
    average_pending_sales_listing_updates DECIMAL(32, 24),
    average_pending_sales_listing_updates_yoy DECIMAL(32, 24),
    average_percent_off_market_in_one_week_listing_updates DECIMAL(32, 24),
    average_percent_off_market_in_one_week_listing_updates_yoy DECIMAL(32, 24),
    average_percent_off_market_in_two_weeks_listing_updates DECIMAL(32, 24),
    average_percent_off_market_in_two_weeks_listing_updates_yoy DECIMAL(32, 24),
    percent_total_price_drops_of_inventory DECIMAL(32, 24),
    percent_total_price_drops_of_inventory_yoy DECIMAL(32, 24),
    percent_homes_sold_above_list DECIMAL(32, 24),
    percent_homes_sold_above_list_yoy DECIMAL(32, 24),
    price_drop_percent_of_old_list_price DECIMAL(32, 24),
    price_drop_percent_of_old_list_price_yoy DECIMAL(32, 24),
    last_updated DATETIME,
    average_adjustment_average_homes_delisted DECIMAL(32, 24),
    adjusted_average_homes_delisted DECIMAL(32, 24),
    average_adjustment_average_homes_sold DECIMAL(32, 24),
    adjusted_average_homes_sold DECIMAL(32, 24),
    average_adjustment_average_new_listings DECIMAL(32, 24),
    adjusted_average_new_listings DECIMAL(32, 24),
    average_adjustment_pending_sales DECIMAL(32, 24),
    adjusted_pending_sales DECIMAL(32, 24),
    adjusted_average_homes_delisted_yoy DECIMAL(32, 24),
    adjusted_average_homes_sold_yoy DECIMAL(32, 24),
    adjusted_average_new_listings_yoy DECIMAL(32, 24),
    adjusted_pending_sales_yoy DECIMAL(32, 24)
);

SELECT * FROM weekly_housing_market_data_most_recent LIMIT 10;

LOAD DATA LOW_PRIORITY LOCAL INFILE 'weekly_housing_market_data_most_recent.tsv'
INTO TABLE `housing`.`weekly_housing_market_data_most_recent`
CHARACTER SET ASCII
FIELDS TERMINATED BY '\t'
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
    @region_id,
    @region_type_id,
    @region_name,
    @region_type,
    @period_begin,
    @period_end,
    @duration,
    @total_homes_sold,
    @total_homes_sold_yoy,
    @average_homes_sold,
    @average_homes_sold_yoy,
    @total_homes_sold_with_price_drops,
    @total_homes_sold_with_price_drops_yoy,
    @average_homes_sold_with_price_drops,
    @average_homes_sold_with_price_drops_yoy,
    @percent_homes_sold_with_price_drops,
    @percent_homes_sold_with_price_drops_yoy,
    @median_sale_price,
    @median_sale_price_yoy,
    @median_sale_ppsf,
    @median_sale_ppsf_yoy,
    @median_days_to_close,
    @median_days_to_close_yoy,
    @price_drops,
    @price_drops_yoy,
    @percent_active_listings_with_price_drops,
    @percent_active_listings_with_price_drops_yoy,
    @pending_sales,
    @pending_sales_yoy,
    @median_pending_sqft,
    @median_pending_sqft_yoy,
    @off_market_in_two_weeks,
    @off_market_in_two_weeks_yoy,
    @off_market_in_one_week,
    @off_market_in_one_week_yoy,
    @percent_off_market_in_two_weeks,
    @percent_off_market_in_two_weeks_yoy,
    @percent_off_market_in_one_week,
    @percent_off_market_in_one_week_yoy,
    @total_new_listings,
    @total_new_listings_yoy,
    @average_new_listings,
    @average_new_listings_yoy,
    @median_new_listing_price,
    @median_new_listing_price_yoy,
    @median_new_listing_ppsf,
    @median_new_listing_ppsf_yoy,
    @inventory,
    @inventory_yoy,
    @total_active_listings,
    @total_active_listings_yoy,
    @active_listings,
    @active_listings_yoy,
    @age_of_inventory,
    @age_of_inventory_yoy,
    @homes_delisted,
    @homes_delisted_yoy,
    @percent_active_listings_delisted,
    @percent_active_listings_delisted_yoy,
    @median_active_list_price,
    @median_active_list_price_yoy,
    @median_active_list_ppsf,
    @median_active_list_ppsf_yoy,
    @average_of_median_list_price_amount,
    @average_of_median_list_price_amount_yoy,
    @average_of_median_offer_price_amount,
    @average_of_median_offer_price_amount_yoy,
    @avg_offer_to_list,
    @avg_offer_to_list_yoy,
    @average_sale_to_list_ratio,
    @average_sale_to_list_ratio_yoy,
    @median_days_on_market,
    @median_days_on_market_yoy,
    @pending_sales_to_sales_ratio,
    @pending_sales_to_sales_ratio_yoy,
    @months_of_supply,
    @months_of_supply_yoy,
    @average_pending_sales_listing_updates,
    @average_pending_sales_listing_updates_yoy,
    @average_percent_off_market_in_one_week_listing_updates,
    @average_percent_off_market_in_one_week_listing_updates_yoy,
    @average_percent_off_market_in_two_weeks_listing_updates,
    @average_percent_off_market_in_two_weeks_listing_updates_yoy,
    @percent_total_price_drops_of_inventory,
    @percent_total_price_drops_of_inventory_yoy,
    @percent_homes_sold_above_list,
    @percent_homes_sold_above_list_yoy,
    @price_drop_percent_of_old_list_price,
    @price_drop_percent_of_old_list_price_yoy,
    @last_updated,
    @average_adjustment_average_homes_delisted,
    @adjusted_average_homes_delisted,
    @average_adjustment_average_homes_sold,
    @adjusted_average_homes_sold,
    @average_adjustment_average_new_listings,
    @adjusted_average_new_listings,
    @average_adjustment_pending_sales,
    @adjusted_pending_sales,
    @adjusted_average_homes_delisted_yoy,
    @adjusted_average_homes_sold_yoy,
    @adjusted_average_new_listings_yoy,
    @adjusted_pending_sales_yoy
)
SET
`region_id` = NULLIF(@region_id, ''),
`region_type_id` = NULLIF(@region_type_id, ''),
`region_name` = NULLIF(@region_name, ''),
`region_type` = NULLIF(@region_type, ''),
`period_begin` = NULLIF(@period_begin, ''),
`period_end` = NULLIF(@period_end, ''),
`duration` = NULLIF(@duration, ''),
`total_homes_sold` = NULLIF(@total_homes_sold, ''),
`total_homes_sold_yoy` = NULLIF(@total_homes_sold_yoy, ''),
`average_homes_sold` = NULLIF(@average_homes_sold, ''),
`average_homes_sold_yoy` = NULLIF(@average_homes_sold_yoy, ''),
`total_homes_sold_with_price_drops` = NULLIF(@total_homes_sold_with_price_drops, ''),
`total_homes_sold_with_price_drops_yoy` = NULLIF(@total_homes_sold_with_price_drops_yoy, ''),
`average_homes_sold_with_price_drops` = NULLIF(@average_homes_sold_with_price_drops, ''),
`average_homes_sold_with_price_drops_yoy` = NULLIF(@average_homes_sold_with_price_drops_yoy, ''),
`percent_homes_sold_with_price_drops` = NULLIF(@percent_homes_sold_with_price_drops, ''),
`percent_homes_sold_with_price_drops_yoy` = NULLIF(@percent_homes_sold_with_price_drops_yoy, ''),
`median_sale_price` = NULLIF(@median_sale_price, ''),
`median_sale_price_yoy` = NULLIF(@median_sale_price_yoy, ''),
`median_sale_ppsf` = NULLIF(@median_sale_ppsf, ''),
`median_sale_ppsf_yoy` = NULLIF(@median_sale_ppsf_yoy, ''),
`median_days_to_close` = NULLIF(@median_days_to_close, ''),
`median_days_to_close_yoy` = NULLIF(@median_days_to_close_yoy, ''),
`price_drops` = NULLIF(@price_drops, ''),
`price_drops_yoy` = NULLIF(@price_drops_yoy, ''),
`percent_active_listings_with_price_drops` = NULLIF(@percent_active_listings_with_price_drops, ''),
`percent_active_listings_with_price_drops_yoy` = NULLIF(@percent_active_listings_with_price_drops_yoy, ''),
`pending_sales` = NULLIF(@pending_sales, ''),
`pending_sales_yoy` = NULLIF(@pending_sales_yoy, ''),
`median_pending_sqft` = NULLIF(@median_pending_sqft, ''),
`median_pending_sqft_yoy` = NULLIF(@median_pending_sqft_yoy, ''),
`off_market_in_two_weeks` = NULLIF(@off_market_in_two_weeks, ''),
`off_market_in_two_weeks_yoy` = NULLIF(@off_market_in_two_weeks_yoy, ''),
`off_market_in_one_week` = NULLIF(@off_market_in_one_week, ''),
`off_market_in_one_week_yoy` = NULLIF(@off_market_in_one_week_yoy, ''),
`percent_off_market_in_two_weeks` = NULLIF(@percent_off_market_in_two_weeks, ''),
`percent_off_market_in_two_weeks_yoy` = NULLIF(@percent_off_market_in_two_weeks_yoy, ''),
`percent_off_market_in_one_week` = NULLIF(@percent_off_market_in_one_week, ''),
`percent_off_market_in_one_week_yoy` = NULLIF(@percent_off_market_in_one_week_yoy, ''),
`total_new_listings` = NULLIF(@total_new_listings, ''),
`total_new_listings_yoy` = NULLIF(@total_new_listings_yoy, ''),
`average_new_listings` = NULLIF(@average_new_listings, ''),
`average_new_listings_yoy` = NULLIF(@average_new_listings_yoy, ''),
`median_new_listing_price` = NULLIF(@median_new_listing_price, ''),
`median_new_listing_price_yoy` = NULLIF(@median_new_listing_price_yoy, ''),
`median_new_listing_ppsf` = NULLIF(@median_new_listing_ppsf, ''),
`median_new_listing_ppsf_yoy` = NULLIF(@median_new_listing_ppsf_yoy, ''),
`inventory` = NULLIF(@inventory, ''),
`inventory_yoy` = NULLIF(@inventory_yoy, ''),
`total_active_listings` = NULLIF(@total_active_listings, ''),
`total_active_listings_yoy` = NULLIF(@total_active_listings_yoy, ''),
`active_listings` = NULLIF(@active_listings, ''),
`active_listings_yoy` = NULLIF(@active_listings_yoy, ''),
`age_of_inventory` = NULLIF(@age_of_inventory, ''),
`age_of_inventory_yoy` = NULLIF(@age_of_inventory_yoy, ''),
`homes_delisted` = NULLIF(@homes_delisted, ''),
`homes_delisted_yoy` = NULLIF(@homes_delisted_yoy, ''),
`percent_active_listings_delisted` = NULLIF(@percent_active_listings_delisted, ''),
`percent_active_listings_delisted_yoy` = NULLIF(@percent_active_listings_delisted_yoy, ''),
`median_active_list_price` = NULLIF(@median_active_list_price, ''),
`median_active_list_price_yoy` = NULLIF(@median_active_list_price_yoy, ''),
`median_active_list_ppsf` = NULLIF(@median_active_list_ppsf, ''),
`median_active_list_ppsf_yoy` = NULLIF(@median_active_list_ppsf_yoy, ''),
`average_of_median_list_price_amount` = NULLIF(@average_of_median_list_price_amount, ''),
`average_of_median_list_price_amount_yoy` = NULLIF(@average_of_median_list_price_amount_yoy, ''),
`average_of_median_offer_price_amount` = NULLIF(@average_of_median_offer_price_amount, ''),
`average_of_median_offer_price_amount_yoy` = NULLIF(@average_of_median_offer_price_amount_yoy, ''),
`avg_offer_to_list` = NULLIF(@avg_offer_to_list, ''),
`avg_offer_to_list_yoy` = NULLIF(@avg_offer_to_list_yoy, ''),
`average_sale_to_list_ratio` = NULLIF(@average_sale_to_list_ratio, ''),
`average_sale_to_list_ratio_yoy` = NULLIF(@average_sale_to_list_ratio_yoy, ''),
`median_days_on_market` = NULLIF(@median_days_on_market, ''),
`median_days_on_market_yoy` = NULLIF(@median_days_on_market_yoy, ''),
`pending_sales_to_sales_ratio` = NULLIF(@pending_sales_to_sales_ratio, ''),
`pending_sales_to_sales_ratio_yoy` = NULLIF(@pending_sales_to_sales_ratio_yoy, ''),
`months_of_supply` = NULLIF(@months_of_supply, ''),
`months_of_supply_yoy` = NULLIF(@months_of_supply_yoy, ''),
`average_pending_sales_listing_updates` = NULLIF(@average_pending_sales_listing_updates, ''),
`average_pending_sales_listing_updates_yoy` = NULLIF(@average_pending_sales_listing_updates_yoy, ''),
`average_percent_off_market_in_one_week_listing_updates` = NULLIF(@average_percent_off_market_in_one_week_listing_updates, ''),
`average_percent_off_market_in_one_week_listing_updates_yoy` = NULLIF(@average_percent_off_market_in_one_week_listing_updates_yoy, ''),
`average_percent_off_market_in_two_weeks_listing_updates` = NULLIF(@average_percent_off_market_in_two_weeks_listing_updates, ''),
`average_percent_off_market_in_two_weeks_listing_updates_yoy` = NULLIF(@average_percent_off_market_in_two_weeks_listing_updates_yoy, ''),
`percent_total_price_drops_of_inventory` = NULLIF(@percent_total_price_drops_of_inventory, ''),
`percent_total_price_drops_of_inventory_yoy` = NULLIF(@percent_total_price_drops_of_inventory_yoy, ''),
`percent_homes_sold_above_list` = NULLIF(@percent_homes_sold_above_list, ''),
`percent_homes_sold_above_list_yoy` = NULLIF(@percent_homes_sold_above_list_yoy, ''),
`price_drop_percent_of_old_list_price` = NULLIF(@price_drop_percent_of_old_list_price, ''),
`price_drop_percent_of_old_list_price_yoy` = NULLIF(@price_drop_percent_of_old_list_price_yoy, ''),
`last_updated` = NULLIF(@last_updated, ''),
`average_adjustment_average_homes_delisted` = NULLIF(@average_adjustment_average_homes_delisted, ''),
`adjusted_average_homes_delisted` = NULLIF(@adjusted_average_homes_delisted, ''),
`average_adjustment_average_homes_sold` = NULLIF(@average_adjustment_average_homes_sold, ''),
`adjusted_average_homes_sold` = NULLIF(@adjusted_average_homes_sold, ''),
`average_adjustment_average_new_listings` = NULLIF(@average_adjustment_average_new_listings, ''),
`adjusted_average_new_listings` = NULLIF(@adjusted_average_new_listings, ''),
`average_adjustment_pending_sales` = NULLIF(@average_adjustment_pending_sales, ''),
`adjusted_pending_sales` = NULLIF(@adjusted_pending_sales, ''),
`adjusted_average_homes_delisted_yoy` = NULLIF(@adjusted_average_homes_delisted_yoy, ''),
`adjusted_average_homes_sold_yoy` = NULLIF(@adjusted_average_homes_sold_yoy, ''),
`adjusted_average_new_listings_yoy` = NULLIF(@adjusted_average_new_listings_yoy, ''),
`adjusted_pending_sales_yoy` = NULLIF(@adjusted_pending_sales_yoy, '');
